# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: real_estate_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19real_estate_service.proto\x12\x06\x61pi_v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n\x12GetListingsRequest\x12)\n\x06\x66ilter\x18\x01 \x01(\x0b\x32\x19.api_v1.GetListingsFilter\x12\x12\n\nnext_token\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"\x95\x01\n\x11GetListingsFilter\x12\x0e\n\x06\x63ities\x18\x01 \x03(\t\x12\x16\n\x0eneighbourhoods\x18\x02 \x03(\t\x12\r\n\x05types\x18\x03 \x03(\t\x12\x11\n\tmin_price\x18\x04 \x01(\x05\x12\x11\n\tmax_price\x18\x05 \x01(\x05\x12#\n\ttime_span\x18\x06 \x01(\x0b\x32\x10.api_v1.TimeSpan\"`\n\x08TimeSpan\x12)\n\x05since\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x05until\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"K\n\x13GetListingsResponse\x12!\n\x08listings\x18\x01 \x03(\x0b\x32\x0f.api_v1.Listing\x12\x11\n\tnextToken\x18\x02 \x01(\t\"\xa1\x02\n\x07Listing\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x12\x1a\n\x04\x63ity\x18\x04 \x01(\x0b\x32\x0c.api_v1.City\x12,\n\rneighbourhood\x18\x05 \x01(\x0b\x32\x15.api_v1.Neighbourhood\x12!\n\x04type\x18\x06 \x01(\x0b\x32\x13.api_v1.ListingType\x12.\n\nadded_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_updated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06mls_id\x18\t \x01(\t\x12\x0b\n\x03url\x18\n \x01(\t\" \n\x04\x43ity\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\")\n\rNeighbourhood\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\'\n\x0bListingType\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t2V\n\nRealEstate\x12H\n\x0bGetListings\x12\x1a.api_v1.GetListingsRequest\x1a\x1b.api_v1.GetListingsResponse\"\x00\x42\x1bZ\x19github.com/tehzwen/api_v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'real_estate_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031github.com/tehzwen/api_v1'
  _GETLISTINGSREQUEST._serialized_start=70
  _GETLISTINGSREQUEST._serialized_end=168
  _GETLISTINGSFILTER._serialized_start=171
  _GETLISTINGSFILTER._serialized_end=320
  _TIMESPAN._serialized_start=322
  _TIMESPAN._serialized_end=418
  _GETLISTINGSRESPONSE._serialized_start=420
  _GETLISTINGSRESPONSE._serialized_end=495
  _LISTING._serialized_start=498
  _LISTING._serialized_end=787
  _CITY._serialized_start=789
  _CITY._serialized_end=821
  _NEIGHBOURHOOD._serialized_start=823
  _NEIGHBOURHOOD._serialized_end=864
  _LISTINGTYPE._serialized_start=866
  _LISTINGTYPE._serialized_end=905
  _REALESTATE._serialized_start=907
  _REALESTATE._serialized_end=993
# @@protoc_insertion_point(module_scope)
